import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import '../styles.css';
import './admin.css';

const emptyBook = { lessonName: '', subject: 'Biology', topics: '', actualPrice: '', discountedPrice: '' };
function AdminApp() {
  const [books, setBooks] = useState([]); const [tab, setTab] = useState('overview'); const [form, setForm] = useState(emptyBook); const [message, setMessage] = useState('Checking your secure admin session…');
  const loadBooks = async () => { const response = await fetch('/api/admin/books', { credentials: 'same-origin' }); if (response.status === 401) return window.location.replace('/setup/admin'); if (!response.ok) return setMessage('Unable to load admin data.'); const data = await response.json(); setBooks(data.books); setMessage(''); };
  useEffect(() => { loadBooks(); }, []);
  const submit = async event => { event.preventDefault(); const response = await fetch('/api/admin/books', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || 'Could not publish this book.'); setForm(emptyBook); setMessage('Book approved and published.'); setTab('books'); loadBooks(); };
  return <div className="admin-shell"><aside className="admin-sidebar"><a className="brand" href="/"><span className="brand-mark">M</span>mednotes</a><p className="admin-caption">SECURE ADMIN</p>{[['overview','Overview'],['add','Add a book'],['books','Books']].map(([key, label]) => <button className={tab === key ? 'admin-nav active' : 'admin-nav'} onClick={() => setTab(key)} key={key}>{label}</button>)}<a className="admin-exit" href="/">← Back to website</a></aside><main className="admin-main"><header className="admin-top"><div><p className="eyebrow">SERVER-PROTECTED CONSOLE</p><h1>{tab === 'overview' ? 'Admin overview.' : tab === 'add' ? 'Add a new book.' : 'Live books.'}</h1></div></header>{message && <p className="admin-message">{message}</p>}{tab === 'overview' && <section className="admin-callout"><div><p className="eyebrow">CATALOGUE</p><h2>{books.length} live books</h2><p>Only Google accounts in the server-side admin allow-list can access this data or publish books.</p></div><button className="primary-button" onClick={() => setTab('add')}>Add a book <span>→</span></button></section>}{tab === 'add' && <form className="book-form" onSubmit={submit}><label>Book / lesson name<input required value={form.lessonName} onChange={e => setForm({...form, lessonName: e.target.value})} /></label><label>Subject category<select value={form.subject} onChange={e => setForm({...form, subject: e.target.value})}><option>Biology</option><option>Physics</option><option>Chemistry</option></select></label><label>Lessons or topics covered<textarea required value={form.topics} onChange={e => setForm({...form, topics: e.target.value})} /></label><div className="price-fields"><label>Actual price (₹)<input required type="number" min="1" value={form.actualPrice} onChange={e => setForm({...form, actualPrice: e.target.value})} /></label><label>Discounted price (₹)<input required type="number" min="1" value={form.discountedPrice} onChange={e => setForm({...form, discountedPrice: e.target.value})} /></label></div><button className="primary-button" type="submit">Approve & publish <span>✓</span></button></form>}{tab === 'books' && <section className="admin-table"><div className="table-head"><span>Book</span><span>Subject</span><span>Price</span><span>Status</span></div>{books.map(book => <div className="table-row" key={book.id}><b>{book.lesson_name}</b><span>{book.subject}</span><span>₹{book.discounted_price}</span><span className="status">{book.status}</span></div>)}</section>}</main></div>;
}
createRoot(document.getElementById('admin-root')).render(<AdminApp />);
