const notes=[
 {id:'bio-human',title:'Human Physiology',subject:'Biology',type:'Notes + 1-on-1 doubt guidance',price:299,mrp:499,theme:'bio'},
 {id:'bio-botany',title:'Plant Physiology',subject:'Biology',type:'Notes + 1-on-1 doubt guidance',price:279,mrp:449,theme:'bio'},
 {id:'phy-mechanics',title:'Mechanics Mastery',subject:'Physics',type:'Notes + 1-on-1 doubt guidance',price:349,mrp:549,theme:'phy'},
 {id:'chem-organic',title:'Organic Chemistry',subject:'Chemistry',type:'Notes + 1-on-1 doubt guidance',price:329,mrp:529,theme:'chem'},
 {id:'phy-electro',title:'Electrodynamics',subject:'Physics',type:'Notes + 1-on-1 doubt guidance',price:319,mrp:499,theme:'phy'},
 {id:'chem-inorganic',title:'Inorganic Chemistry',subject:'Chemistry',type:'Notes + 1-on-1 doubt guidance',price:299,mrp:479,theme:'chem'}
];
let cart=JSON.parse(localStorage.getItem('mednotes-cart')||'[]');let owned=JSON.parse(localStorage.getItem('mednotes-library')||'[]');let filter='All';
const money=n=>'₹'+n.toLocaleString('en-IN');const grid=document.querySelector('#productGrid');
function renderProducts(){grid.innerHTML=notes.filter(n=>filter==='All'||n.subject===filter).map(n=>`<article class="product"><div class="cover ${n.theme}"><span>${n.subject.toUpperCase()} / NEET 2026</span><b>${n.title}</b><span>${n.type.toUpperCase()}</span></div><div class="product-info"><h3>${n.title}</h3><p>${n.type}</p><div class="price"><b>${money(n.price)}</b><del>${money(n.mrp)}</del><button class="add" aria-label="Add ${n.title}" data-add="${n.id}">+</button></div></div></article>`).join('');}
function save(){localStorage.setItem('mednotes-cart',JSON.stringify(cart));localStorage.setItem('mednotes-library',JSON.stringify(owned));}
function renderCart(){document.querySelector('#cartCount').textContent=cart.length;const box=document.querySelector('#cartItems');box.innerHTML=cart.length?cart.map(id=>{const n=notes.find(x=>x.id===id);return `<div class="cart-item"><div class="mini-cover ${n.theme}">${n.subject}</div><div><b>${n.title}</b><p>${n.type}</p><strong>${money(n.price)}</strong></div><button class="remove" data-remove="${id}">×</button></div>`}).join(''):'<p class="empty">Your plan is empty. Choose a subject to get notes and a guide for your doubts.</p>';document.querySelector('#cartTotal').textContent=money(cart.reduce((s,id)=>s+notes.find(x=>x.id===id).price,0));}
function renderLibrary(){const el=document.querySelector('#libraryContent');el.innerHTML=owned.length?owned.map(id=>{const n=notes.find(x=>x.id===id);return `<article class="library-card"><p class="eyebrow">${n.subject.toUpperCase()} · ACTIVE SUPPORT</p><h3>${n.title}</h3><p>Read your notes here, or send a doubt to your 1-on-1 guide for this subject.</p><button class="read-button" data-read="${id}">Open notes →</button> <button class="read-button" data-doubt="${id}">Ask a doubt →</button></article>`}).join(''):'<p class="empty">Your dashboard will show your notes and personal doubt support here.</p>';}
function showToast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function openDrawer(id){document.querySelector('#'+id).classList.add('open');document.querySelector('#backdrop').classList.add('visible')};function closeDrawers(){document.querySelectorAll('.drawer').forEach(x=>x.classList.remove('open'));document.querySelector('#backdrop').classList.remove('visible')}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){const id=add.dataset.add;if(!cart.includes(id)){cart.push(id);save();renderCart();showToast('Support plan added.')}else showToast('This support plan is already selected.');}const remove=e.target.closest('[data-remove]');if(remove){cart=cart.filter(id=>id!==remove.dataset.remove);save();renderCart()}const read=e.target.closest('[data-read]');if(read)showToast('The protected notes reader opens here after deployment.');const doubt=e.target.closest('[data-doubt]');if(doubt)showToast('Your doubt request form will open here after deployment.');});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');filter=b.dataset.filter;renderProducts()}));
document.querySelector('#cartButton').onclick=()=>openDrawer('cartDrawer');document.querySelector('#accountButton').onclick=()=>document.querySelector('#authModal').showModal();document.querySelector('#adminButton').onclick=()=>document.querySelector('#adminModal').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeDrawers);document.querySelector('#backdrop').onclick=closeDrawers;document.querySelectorAll('.modal-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelector('#authForm').onsubmit=e=>{e.preventDefault();e.target.closest('dialog').close();renderLibrary();openDrawer('libraryDrawer');showToast('Welcome back. Your guidance space is ready.');};document.querySelector('#adminForm').onsubmit=e=>{e.preventDefault();e.target.closest('dialog').close();showToast('Admin dashboard will be connected after deployment.');};
document.querySelector('#checkoutButton').onclick=()=>{if(!cart.length)return showToast('Choose a subject support plan before continuing.');owned=[...new Set([...owned,...cart])];cart=[];save();renderCart();renderLibrary();closeDrawers();openDrawer('libraryDrawer');showToast('Demo plan activated — your notes and doubt support are ready.');};
renderProducts();renderCart();renderLibrary();
